#!/bin/bash

/usr/local/bin/electrs -v --timestamp --jsonrpc-import --http-addr "${HTTP_ADDR}" --monitoring-addr "${MONITORING_ADDR}" --daemon-rpc-addr "${DAEMON_RPC_ADDR}" --cookie "${COOKIE}" --network "${NETWORK}"